from experiments import env_testing_advanced_prioritized_symbolic
env_testing_advanced_prioritized_symbolic.test_run()
# env_testing_advanced_prioritized_symbolic.check_filter()
# env_testing_advanced_prioritized_symbolic.plot_prices_and_costs()